name: ema_app
description: "EMA - Emergência, Monitoramento e Apoio (MVP mock frontend)"
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.0
  google_fonts: ^4.0.4
  flutter_riverpod: ^2.0.0
  dio: ^5.0.0
  geolocator: ^9.0.0
  google_maps_flutter: ^2.0.0
  google_maps_flutter_web: ^0.3.0
  flutter_animate: ^4.0.0
  url_launcher: ^6.1.5
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/sos_event.json
    - assets/json/location_stream.json
    - assets/json/contacts.json
    - assets/json/safety_tips.json
    - assets/json/users.json
